/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tac_toe;

/**
 *
 * @author Matthew
 */
public class PlayArea_GUI extends javax.swing.JFrame {
    /**
     * Creates new form PlayArea_GUI
     */
    public PlayArea_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticTacToeArea = new javax.swing.JPanel();
        ticTacToeSquare_0 = new javax.swing.JPanel();
        ticTacToeSquare_1 = new javax.swing.JPanel();
        ticTacToeSquare_2 = new javax.swing.JPanel();
        ticTacToeSquare_3 = new javax.swing.JPanel();
        ticTacToeSquare_4 = new javax.swing.JPanel();
        ticTacToeSquare_5 = new javax.swing.JPanel();
        ticTacToeSquare_6 = new javax.swing.JPanel();
        ticTacToeSquare_7 = new javax.swing.JPanel();
        ticTacToeSquare_8 = new javax.swing.JPanel();
        userInfoArea = new javax.swing.JPanel();
        howToPlay_Btn = new javax.swing.JButton();
        undo_Btn = new javax.swing.JButton();
        restart_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        playerTurn_Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticTacToeArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ticTacToeSquare_0.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_0.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_0Layout = new javax.swing.GroupLayout(ticTacToeSquare_0);
        ticTacToeSquare_0.setLayout(ticTacToeSquare_0Layout);
        ticTacToeSquare_0Layout.setHorizontalGroup(
            ticTacToeSquare_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_0Layout.setVerticalGroup(
            ticTacToeSquare_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_1.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_1.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_1Layout = new javax.swing.GroupLayout(ticTacToeSquare_1);
        ticTacToeSquare_1.setLayout(ticTacToeSquare_1Layout);
        ticTacToeSquare_1Layout.setHorizontalGroup(
            ticTacToeSquare_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_1Layout.setVerticalGroup(
            ticTacToeSquare_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_2.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_2.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_2Layout = new javax.swing.GroupLayout(ticTacToeSquare_2);
        ticTacToeSquare_2.setLayout(ticTacToeSquare_2Layout);
        ticTacToeSquare_2Layout.setHorizontalGroup(
            ticTacToeSquare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_2Layout.setVerticalGroup(
            ticTacToeSquare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_3.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_3.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_3Layout = new javax.swing.GroupLayout(ticTacToeSquare_3);
        ticTacToeSquare_3.setLayout(ticTacToeSquare_3Layout);
        ticTacToeSquare_3Layout.setHorizontalGroup(
            ticTacToeSquare_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_3Layout.setVerticalGroup(
            ticTacToeSquare_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_4.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_4.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_4Layout = new javax.swing.GroupLayout(ticTacToeSquare_4);
        ticTacToeSquare_4.setLayout(ticTacToeSquare_4Layout);
        ticTacToeSquare_4Layout.setHorizontalGroup(
            ticTacToeSquare_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_4Layout.setVerticalGroup(
            ticTacToeSquare_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_5.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_5.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_5Layout = new javax.swing.GroupLayout(ticTacToeSquare_5);
        ticTacToeSquare_5.setLayout(ticTacToeSquare_5Layout);
        ticTacToeSquare_5Layout.setHorizontalGroup(
            ticTacToeSquare_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_5Layout.setVerticalGroup(
            ticTacToeSquare_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_6.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_6.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_6Layout = new javax.swing.GroupLayout(ticTacToeSquare_6);
        ticTacToeSquare_6.setLayout(ticTacToeSquare_6Layout);
        ticTacToeSquare_6Layout.setHorizontalGroup(
            ticTacToeSquare_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_6Layout.setVerticalGroup(
            ticTacToeSquare_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_7.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_7.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_7Layout = new javax.swing.GroupLayout(ticTacToeSquare_7);
        ticTacToeSquare_7.setLayout(ticTacToeSquare_7Layout);
        ticTacToeSquare_7Layout.setHorizontalGroup(
            ticTacToeSquare_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_7Layout.setVerticalGroup(
            ticTacToeSquare_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        ticTacToeSquare_8.setBackground(new java.awt.Color(255, 255, 255));
        ticTacToeSquare_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticTacToeSquare_8.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout ticTacToeSquare_8Layout = new javax.swing.GroupLayout(ticTacToeSquare_8);
        ticTacToeSquare_8.setLayout(ticTacToeSquare_8Layout);
        ticTacToeSquare_8Layout.setHorizontalGroup(
            ticTacToeSquare_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        ticTacToeSquare_8Layout.setVerticalGroup(
            ticTacToeSquare_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ticTacToeAreaLayout = new javax.swing.GroupLayout(ticTacToeArea);
        ticTacToeArea.setLayout(ticTacToeAreaLayout);
        ticTacToeAreaLayout.setHorizontalGroup(
            ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticTacToeAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ticTacToeAreaLayout.createSequentialGroup()
                        .addComponent(ticTacToeSquare_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ticTacToeSquare_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ticTacToeAreaLayout.createSequentialGroup()
                            .addComponent(ticTacToeSquare_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(ticTacToeSquare_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ticTacToeAreaLayout.createSequentialGroup()
                            .addComponent(ticTacToeSquare_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ticTacToeSquare_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticTacToeSquare_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticTacToeSquare_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticTacToeSquare_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        ticTacToeAreaLayout.setVerticalGroup(
            ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticTacToeAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ticTacToeSquare_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ticTacToeSquare_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ticTacToeSquare_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticTacToeSquare_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticTacToeSquare_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticTacToeSquare_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticTacToeAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ticTacToeSquare_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ticTacToeSquare_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ticTacToeSquare_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        userInfoArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        howToPlay_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        howToPlay_Btn.setText("How to play?");

        undo_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        undo_Btn.setText("Undo");

        restart_Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        restart_Btn.setText("Restart");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Players Info.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Player 1: X");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Player 2: O");

        playerTurn_Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        playerTurn_Label.setText("Player 1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Who's Turn?");

        javax.swing.GroupLayout userInfoAreaLayout = new javax.swing.GroupLayout(userInfoArea);
        userInfoArea.setLayout(userInfoAreaLayout);
        userInfoAreaLayout.setHorizontalGroup(
            userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoAreaLayout.createSequentialGroup()
                .addGroup(userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(undo_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(howToPlay_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restart_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(userInfoAreaLayout.createSequentialGroup()
                        .addGroup(userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoAreaLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)))
                            .addGroup(userInfoAreaLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(playerTurn_Label))
                            .addGroup(userInfoAreaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        userInfoAreaLayout.setVerticalGroup(
            userInfoAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userInfoAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTurn_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(howToPlay_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(undo_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restart_Btn)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ticTacToeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userInfoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userInfoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ticTacToeArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayArea_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayArea_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayArea_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayArea_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayArea_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton howToPlay_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel playerTurn_Label;
    private javax.swing.JButton restart_Btn;
    private javax.swing.JPanel ticTacToeArea;
    private javax.swing.JPanel ticTacToeSquare_0;
    private javax.swing.JPanel ticTacToeSquare_1;
    private javax.swing.JPanel ticTacToeSquare_2;
    private javax.swing.JPanel ticTacToeSquare_3;
    private javax.swing.JPanel ticTacToeSquare_4;
    private javax.swing.JPanel ticTacToeSquare_5;
    private javax.swing.JPanel ticTacToeSquare_6;
    private javax.swing.JPanel ticTacToeSquare_7;
    private javax.swing.JPanel ticTacToeSquare_8;
    private javax.swing.JButton undo_Btn;
    private javax.swing.JPanel userInfoArea;
    // End of variables declaration//GEN-END:variables
}
